/* This file was automatically generated by CasADi 3.6.7.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) GemCarModel_expl_ode_hess_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s1[23] = {4, 4, 0, 4, 8, 12, 16, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3};
static const casadi_int casadi_s2[13] = {4, 2, 0, 4, 8, 0, 1, 2, 3, 0, 1, 2, 3};
static const casadi_int casadi_s3[6] = {2, 1, 0, 2, 0, 1};
static const casadi_int casadi_s4[3] = {0, 0, 0};
static const casadi_int casadi_s5[10] = {6, 1, 0, 6, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s6[25] = {21, 1, 0, 21, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20};

/* GemCarModel_expl_ode_hess:(i0[4],i1[4x4],i2[4x2],i3[4],i4[2],i5[])->(o0[6],o1[21]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a24, a25, a26, a27, a3, a4, a5, a6, a7, a8, a9;
  a0=0.;
  if (res[0]!=0) res[0][0]=a0;
  if (res[0]!=0) res[0][1]=a0;
  a0=arg[0]? arg[0][2] : 0;
  a1=cos(a0);
  a2=arg[0]? arg[0][3] : 0;
  a3=arg[3]? arg[3][1] : 0;
  a4=(a2*a3);
  a5=(a1*a4);
  a6=sin(a0);
  a7=arg[3]? arg[3][0] : 0;
  a8=(a2*a7);
  a9=(a6*a8);
  a5=(a5-a9);
  if (res[0]!=0) res[0][2]=a5;
  a5=arg[4]? arg[4][1] : 0;
  a9=tan(a5);
  a10=2.6499999999999999e+00;
  a11=arg[3]? arg[3][2] : 0;
  a10=(a10*a11);
  a9=(a9*a10);
  a11=sin(a0);
  a11=(a11*a3);
  a9=(a9+a11);
  a11=cos(a0);
  a11=(a11*a7);
  a9=(a9+a11);
  if (res[0]!=0) res[0][3]=a9;
  a9=arg[3]? arg[3][3] : 0;
  if (res[0]!=0) res[0][4]=a9;
  a2=(a2*a10);
  a9=cos(a5);
  a11=casadi_sq(a9);
  a2=(a2/a11);
  if (res[0]!=0) res[0][5]=a2;
  a12=arg[1]? arg[1][2] : 0;
  a13=arg[1]? arg[1][3] : 0;
  a14=(a3*a13);
  a14=(a1*a14);
  a15=sin(a0);
  a16=(a15*a12);
  a16=(a4*a16);
  a14=(a14-a16);
  a16=cos(a0);
  a17=(a16*a12);
  a17=(a8*a17);
  a18=(a7*a13);
  a18=(a6*a18);
  a17=(a17+a18);
  a14=(a14-a17);
  a17=(a12*a14);
  a18=cos(a0);
  a19=(a18*a12);
  a19=(a3*a19);
  a0=sin(a0);
  a12=(a0*a12);
  a12=(a7*a12);
  a19=(a19-a12);
  a12=(a13*a19);
  a17=(a17+a12);
  if (res[1]!=0) res[1][0]=a17;
  a17=arg[1]? arg[1][6] : 0;
  a12=(a17*a14);
  a20=arg[1]? arg[1][7] : 0;
  a21=(a20*a19);
  a12=(a12+a21);
  if (res[1]!=0) res[1][1]=a12;
  a12=arg[1]? arg[1][10] : 0;
  a21=(a12*a14);
  a22=arg[1]? arg[1][11] : 0;
  a23=(a22*a19);
  a21=(a21+a23);
  if (res[1]!=0) res[1][2]=a21;
  a21=arg[1]? arg[1][14] : 0;
  a23=(a21*a14);
  a24=arg[1]? arg[1][15] : 0;
  a25=(a24*a19);
  a23=(a23+a25);
  if (res[1]!=0) res[1][3]=a23;
  a23=arg[2]? arg[2][2] : 0;
  a25=(a23*a14);
  a26=arg[2]? arg[2][3] : 0;
  a27=(a26*a19);
  a25=(a25+a27);
  if (res[1]!=0) res[1][4]=a25;
  a25=arg[2]? arg[2][6] : 0;
  a14=(a25*a14);
  a27=arg[2]? arg[2][7] : 0;
  a19=(a27*a19);
  a14=(a14+a19);
  a13=(a10*a13);
  a13=(a13/a11);
  a14=(a14+a13);
  if (res[1]!=0) res[1][5]=a14;
  a14=(a3*a20);
  a14=(a1*a14);
  a13=(a15*a17);
  a13=(a4*a13);
  a14=(a14-a13);
  a13=(a16*a17);
  a13=(a8*a13);
  a19=(a7*a20);
  a19=(a6*a19);
  a13=(a13+a19);
  a14=(a14-a13);
  a13=(a17*a14);
  a19=(a18*a17);
  a19=(a3*a19);
  a17=(a0*a17);
  a17=(a7*a17);
  a19=(a19-a17);
  a17=(a20*a19);
  a13=(a13+a17);
  if (res[1]!=0) res[1][6]=a13;
  a13=(a12*a14);
  a17=(a22*a19);
  a13=(a13+a17);
  if (res[1]!=0) res[1][7]=a13;
  a13=(a21*a14);
  a17=(a24*a19);
  a13=(a13+a17);
  if (res[1]!=0) res[1][8]=a13;
  a13=(a23*a14);
  a17=(a26*a19);
  a13=(a13+a17);
  if (res[1]!=0) res[1][9]=a13;
  a14=(a25*a14);
  a19=(a27*a19);
  a14=(a14+a19);
  a20=(a10*a20);
  a20=(a20/a11);
  a14=(a14+a20);
  if (res[1]!=0) res[1][10]=a14;
  a14=(a3*a22);
  a14=(a1*a14);
  a20=(a15*a12);
  a20=(a4*a20);
  a14=(a14-a20);
  a20=(a16*a12);
  a20=(a8*a20);
  a19=(a7*a22);
  a19=(a6*a19);
  a20=(a20+a19);
  a14=(a14-a20);
  a20=(a12*a14);
  a19=(a18*a12);
  a19=(a3*a19);
  a12=(a0*a12);
  a12=(a7*a12);
  a19=(a19-a12);
  a12=(a22*a19);
  a20=(a20+a12);
  if (res[1]!=0) res[1][11]=a20;
  a20=(a21*a14);
  a12=(a24*a19);
  a20=(a20+a12);
  if (res[1]!=0) res[1][12]=a20;
  a20=(a23*a14);
  a12=(a26*a19);
  a20=(a20+a12);
  if (res[1]!=0) res[1][13]=a20;
  a14=(a25*a14);
  a19=(a27*a19);
  a14=(a14+a19);
  a22=(a10*a22);
  a22=(a22/a11);
  a14=(a14+a22);
  if (res[1]!=0) res[1][14]=a14;
  a14=(a3*a24);
  a14=(a1*a14);
  a22=(a15*a21);
  a22=(a4*a22);
  a14=(a14-a22);
  a22=(a16*a21);
  a22=(a8*a22);
  a19=(a7*a24);
  a19=(a6*a19);
  a22=(a22+a19);
  a14=(a14-a22);
  a22=(a21*a14);
  a19=(a18*a21);
  a19=(a3*a19);
  a21=(a0*a21);
  a21=(a7*a21);
  a19=(a19-a21);
  a21=(a24*a19);
  a22=(a22+a21);
  if (res[1]!=0) res[1][15]=a22;
  a22=(a23*a14);
  a21=(a26*a19);
  a22=(a22+a21);
  if (res[1]!=0) res[1][16]=a22;
  a14=(a25*a14);
  a19=(a27*a19);
  a14=(a14+a19);
  a24=(a10*a24);
  a24=(a24/a11);
  a14=(a14+a24);
  if (res[1]!=0) res[1][17]=a14;
  a14=(a3*a26);
  a14=(a1*a14);
  a24=(a15*a23);
  a24=(a4*a24);
  a14=(a14-a24);
  a24=(a16*a23);
  a24=(a8*a24);
  a19=(a7*a26);
  a19=(a6*a19);
  a24=(a24+a19);
  a14=(a14-a24);
  a24=(a23*a14);
  a19=(a18*a23);
  a19=(a3*a19);
  a23=(a0*a23);
  a23=(a7*a23);
  a19=(a19-a23);
  a23=(a26*a19);
  a24=(a24+a23);
  if (res[1]!=0) res[1][18]=a24;
  a14=(a25*a14);
  a19=(a27*a19);
  a14=(a14+a19);
  a26=(a10*a26);
  a26=(a26/a11);
  a14=(a14+a26);
  if (res[1]!=0) res[1][19]=a14;
  a14=(a3*a27);
  a1=(a1*a14);
  a15=(a15*a25);
  a4=(a4*a15);
  a1=(a1-a4);
  a16=(a16*a25);
  a8=(a8*a16);
  a16=(a7*a27);
  a6=(a6*a16);
  a8=(a8+a6);
  a1=(a1-a8);
  a1=(a25*a1);
  a8=cos(a5);
  a8=casadi_sq(a8);
  a8=(a10/a8);
  a18=(a18*a25);
  a3=(a3*a18);
  a8=(a8+a3);
  a0=(a0*a25);
  a7=(a7*a0);
  a8=(a8-a7);
  a8=(a27*a8);
  a1=(a1+a8);
  a10=(a10*a27);
  a10=(a10/a11);
  a2=(a2/a11);
  a9=(a9+a9);
  a5=sin(a5);
  a9=(a9*a5);
  a2=(a2*a9);
  a10=(a10+a2);
  a1=(a1+a10);
  if (res[1]!=0) res[1][20]=a1;
  return 0;
}

CASADI_SYMBOL_EXPORT int GemCarModel_expl_ode_hess(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int GemCarModel_expl_ode_hess_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int GemCarModel_expl_ode_hess_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void GemCarModel_expl_ode_hess_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int GemCarModel_expl_ode_hess_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void GemCarModel_expl_ode_hess_release(int mem) {
}

CASADI_SYMBOL_EXPORT void GemCarModel_expl_ode_hess_incref(void) {
}

CASADI_SYMBOL_EXPORT void GemCarModel_expl_ode_hess_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int GemCarModel_expl_ode_hess_n_in(void) { return 6;}

CASADI_SYMBOL_EXPORT casadi_int GemCarModel_expl_ode_hess_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_real GemCarModel_expl_ode_hess_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* GemCarModel_expl_ode_hess_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    case 5: return "i5";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* GemCarModel_expl_ode_hess_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* GemCarModel_expl_ode_hess_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s0;
    case 4: return casadi_s3;
    case 5: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* GemCarModel_expl_ode_hess_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s5;
    case 1: return casadi_s6;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int GemCarModel_expl_ode_hess_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int GemCarModel_expl_ode_hess_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 2*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
